### ISSUE TITLE
Some help getting this running

### ISSUE THREAD

**Issue by IshmaelObeso** [cpyarger/Home-Assistant-Addons#1]
Hello!
I do not have any experience getting readings from my gas meter, so I've been trying to get this component running because it seems to simplify the process quite a bit. What I've done so far is run it with msgtype: [all] for a night to (hopefully) read the meters around me and see what is around. The add-on created some sensors, for example one called [sensor.701102524] and I see the value of the sensor continually going up, so I assume this is a meter from either my house, or somewhere near my house. However, my next step was to run it wish msgtype: scm, with id: [701102524] (I figure that's the device ID from the sensor). However, now I get this error 

/run.sh: line 57: [[701102524: not found

I'm not sure if this is an error with the script, or I'm doing something completely wrong.
Any help would be appreciated, thank you!

**Comment by cpyarger** [comment]
first, look at your meter, it should have the id on it somewhere. second, try 701102524 not [701102524]

**Comment by cpyarger** [comment]
Did this solve your issue?
