### ISSUE TITLE
User Questions

### ISSUE THREAD

**Issue by SpaceCadetRick** [cpyarger/Home-Assistant-Addons#12]
I started using your SDR Meter Reader add-on today and had a couple questions. I first ran it in msgType: all and then narrowed it down to msgType: scm before finding the ID that matched my gas meter however as a result I now have all of the sensor.xxxxxxxx data for all of the different meters that I picked up. How do I remove those?

My second question is how do I add a second meter id to watch for? When I add a second id separated by a comma it tells me "xxxxxxxxx, " is not a valid id and if I try to add each one in quotes it just deletes the second number.

Edit. After posting I tried it like this "ids: 1234,5678" and so far I've been getting readings for 1234, my gas meter, but my water meter, 5678, hasn't popped up yet though it may only wake up when they come around every month to read it.

**Comment by pasyn** [comment]
Any extra sensor IDs should be dumped on a reboot of home assistant because these sensors are saved as states instead of true entities. 

Make sure all is set for msgtype as water and electric tend to use different protocols. You can also turn on the debug switch and watch the log to see if the sdr is picking up the water meter.

**Comment by SpaceCadetRick** [comment]
With the default 15s duration followed by 30s pause would a reading sent while paused get missed?

**Comment by pasyn** [comment]
Possibly. I'll have to look back through the code to see how it works. 120 for duration and 30 for pause time works well for me.

**Comment by SpaceCadetRick** [comment]
I'm having another issue, the entity created is just reporting a number without any of the unit_of_measurement or state_class attributes set. I'm able to add these using developer tools but they get overwritten the next time the entity updates.
![Screenshot_20220601-164958](https://user-images.githubusercontent.com/76118485/171514366-48370560-d65c-4a98-ad04-765448261750.png)

**Comment by pasyn** [comment]
For some reason the addon is not parsing the sdr data correctly. Please turn on debug mode and post the json output from the log relevant to that meter.

**Comment by SpaceCadetRick** [comment]
Yea, as certain as I can be. The ID number matches and the consumption 
has matched the meter reading on multiple occasions.

**Comment by pasyn** [comment]
Excellent! I'm going to close this issue. Feel free to open another if you run into any other problems.

**Comment by cpyarger** [comment]
@pasyn just an FYI, 12 was not included because it can be either a gas or electric meter 
we may want to keep that in mind if we get an electric meter of type 12 
https://github.com/bemasher/rtlamr/blob/master/meters.md

**Comment by pasyn** [comment]
Thank you for pointing that out. That could make things messy. Looking at meters.csv in the rtlamr repository, the Schlumberger CENTRON OOK RF is the only electric meter with type 12. Most of the meters with type 12 are gas. I think gas should be the default for 12 given that there is only one exception. Do you think it would be possible to identify the Schlumberger meter based on the ID? I've noticed that many meters have the same first three digits. Maybe this prefix could be linked to a manufacturer.

**Comment by cpyarger** [comment]
I agree about gas being the default. 

I am not sure, does it use the same message type, if its a difference between scm and scm+ maybe we can do the determination there. Currently we don't really set any variables based on that message type change and just run both through the scmplus parse function
