### ISSUE TITLE
Add additional gas meter type 30

### ISSUE THREAD

**Issue by cbird527** [cpyarger/Home-Assistant-Addons#14]
Can you add an additional gas meter type for Protocol ID 30?
Below is an example of the output of my gas meter
```
{
    "Time": "2022-06-20T12:24:13.751342404-04:00",
    "Offset": 0,
    "Length": 0,
    "Type": "SCM+",
    "Message": {
        "FrameSync": 5795,
        "ProtocolID": 30,
        "EndpointType": 188,
        "EndpointID": 123456789,
        "Consumption": 601532,
        "Tamper": 2056,
        "PacketCRC": 57150
    }
}
```

**Comment by pasyn** [comment]
I have not seen this ID before. The following link is for the RTLAMR meter database. It is what the sdrmr addon uses as a reference for meter types. Use the link to submit your meter to the database and then it can be added to sdrmr addon. 

[https://github.com/bemasher/rtlamr/blob/master/meters.md](https://github.com/bemasher/rtlamr/blob/master/meters.md)

**Comment by cpyarger** [comment]
We aren't filtering by protocol ID. only Endpoint Type. 
188 isnt currently on the list so it should be a quick change to add it to the is gas function

**Comment by cbird527** [comment]
If you could add endpoint type 188 to the gas function.  I having trouble getting my gas values to be selectable in the energy dashboard.  It just shows "No matching statistics found" in the drop down and I am hoping this change would help
