### ISSUE TITLE
Add ability to format consumption values as decimals

### ISSUE THREAD

**Issue by cbird527** [cpyarger/Home-Assistant-Addons#15]
My water meter reports values in tenths of gallons. Is it possible to make the value shown in this output show as 253999.8 gal?

```
{
    "Time": "2022-06-20T11:16:41.373827852-04:00",
    "Offset": 0,
    "Length": 0,
    "Type": "R900",
    "Message": {
        "ID": 123456789,
        "Unkn1": 163,
        "NoUse": 1,
        "BackFlow": 0,
        "Consumption": 2539998,
        "Unkn3": 0,
        "Leak": 3,
        "LeakNow": 0
    }
}
```

**Comment by pasyn** [comment]
Should be doable although I may not have time to submit a PR until this weekend. Many water meters report the same way. What is the make and model of your meter?

**Comment by cbird527** [comment]
The meter is a Neptune E-coder R900i DL, Part No. RD2G11

**Comment by pasyn** [comment]
@cbird527 update to the latest version and enable the water_use_tenths toggle.

**Comment by cbird527** [comment]
Thanks for the update, works great!
