### ISSUE TITLE
SDR Meter Reader - Electric meter readings do not set state attributes

### ISSUE THREAD

**Issue by pasyn** [cpyarger/Home-Assistant-Addons#2]
Water meter which is R900 correctly records state attributes while electric meter which is SCM does not record any state attributes

![Screenshot from 2022-05-01 20-41-13](https://user-images.githubusercontent.com/67178218/166171986-3a8a0007-7249-4311-ad86-55dc862b611d.png)
First screencap is from water meter which is working correctly.

![Screenshot from 2022-05-01 20-41-42](https://user-images.githubusercontent.com/67178218/166171984-9ab5e241-e5f2-47be-9b38-0ecf9faccd63.png)
Second screencap is from electric meter which does not work.

Here is my current sdr meter reader config

```
debug: false
msgType: all
ids: 23876447,1540559732
duration: 15
pause_time: 30
gas_unit_of_measurement: ft³
electric_unit_of_measurement: kWh
water_unit_of_measurement: gal
scm_plus_gas_divisor: 1
```

Electric meter is an Itron CL200
SDR is Nooelec RTL-SDR, FM+DAB, DVB-T USB Stick Set with RTL2832U & R820T
I am running the latest haos on a Raspi 4

Tried to grab some relevant portions of the log. It is difficult to catch the right data as the program seems to only run for a time and then restart.

```
Sending  {"state":"3438056","extra_state_attributes":{"unique_id":"1540559732-sdrmr"},"attributes":{"entity_id":"1540559732-sdrmr","state_class":"total_increasing","unit_of_measurement":"gal","leak":"0","leak_now":"0","BackFlow":"0","NoUse":"32","Unknown1":"163","Unknown3":"0"}}  to http://supervisor/core/api/states/sensor.1540559732 -- 200

Sending  {"state":"22257"}  to http://supervisor/core/api/states/sensor.23876447 -- 200
4
```

Please let me know if I can provide any other information

**Comment by cpyarger** [comment]
Can you turn debug mode on, and send me the raw json that is returned from rtlamr, it will be posted directly above the line starting in "Sending"

There is a toggle switch under the "Configuration" menu used to turn on debug mode. 

Thank you for posting the issue, I only have SCM+ meters nearby so I haven't been able to run through testing the code for SCM yet. 

Also, feel free to blast a handful of the messages instead of just one

**Comment by pasyn** [comment]
Is this what you are referring to?

```
{"Time":"2022-05-01T21:29:19.790169418-04:00","Offset":0,"Length":0,"Type":"SCM","Message":{"ID":23876447,"Type":4,"TamperPhy":0,"TamperEnc":2,"Consumption":22260,"ChecksumVal":11288}}
Sending  {"state":"22260"}  to http://supervisor/core/api/states/sensor.23876447 -- 200
```

**Comment by cpyarger** [comment]
Yupp

**Comment by cpyarger** [comment]
Check for updates, I just pushed a possible fix

**Comment by pasyn** [comment]
Updated and now getting the following error

```
{"Time":"2022-05-01T22:16:24.839155645-04:00","Offset":0,"Length":0,"Type":"SCM","Message":{"ID":23876447,"Type":4,"TamperPhy":0,"TamperEnc":2,"Consumption":22264,"ChecksumVal":25199}}
/run.sh: line 101: [: missing `]'
/run.sh: line 101: SCM: command not found
Sending  {"state":"22264"}  to http://supervisor/core/api/states/sensor.23876447 -- 200
```

**Comment by cpyarger** [comment]
I think I may have miswritten the `or` statement, Pushed a fix

**Comment by pasyn** [comment]
run.sh error is fixed and unique_id attribute is being recorded.

Other attributes are not getting recorded. Looks like either $EPT is being set to an incorrect value or is_electric()  does not include the correct value in the LIST


```
{"Time":"2022-05-01T23:57:52.766512217-04:00","Offset":0,"Length":0,"Type":"SCM","Message":{"ID":23876447,"Type":4,"TamperPhy":0,"TamperEnc":2,"Consumption":22271,"ChecksumVal":4103}}
Sending  {"state":"22271","attributes":{"unique_id":"23876447-sdrmr"}}  to http://supervisor/core/api/states/sensor.23876447 -- 200
```

**Comment by cpyarger** [comment]
Ahh, Endpoint type for SCM+ is returned as Message.EndpointType, for SCM it is Message.Type 
I put a check in to see if the $EPT value is empty, and it sets $EPT to Message.Type if it is.

**Comment by pasyn** [comment]
No change in the log with 0.8.18. Looks like it is still not grabbing the correct type from the json output.

```
{"Time":"2022-05-02T07:24:37.453867711-04:00","Offset":0,"Length":0,"Type":"SCM","Message":{"ID":23876447,"Type":4,"TamperPhy":0,"TamperEnc":2,"Consumption":22281,"ChecksumVal":44665}}
Sending  {"state":"22281","attributes":{"unique_id":"23876447-sdrmr"}}  to http://supervisor/core/api/states/sensor.23876447 -- 200
```

**Comment by cpyarger** [comment]
Not sure this one is going to work, but let me know

**Comment by cpyarger** [comment]
I'll take a look at it this evening when I get home

**Comment by cpyarger** [comment]
Got it, I needed to do 
```bash 
EPT="$(echo $line | jq -rc '.Message.EndpointType' | tr -s ' ' '_')"
  if [ ! -z "$EPT" ]; then
    EPT="$(echo $line | jq -rc '.Message.Type' | tr -s ' ' '_')"
  fi
```
and not 
```bash
EPT="$(echo $line | jq -rc '.Message.EndpointType' | tr -s ' ' '_')"
  if [ -z "$EPT" ]; then
    EPT="$(echo $line | jq -rc '.Message.Type' | tr -s ' ' '_')"
  fi
```

**Comment by cpyarger** [comment]
dumb stupid rookie mistake, sorry

**Comment by pasyn** [comment]
No worries! I would have missed that as well.

The latest version is still not recognizing the SCM meter type as electric. is_electric does not return a true value when EPT = 4 due to the =~ operator comparing the strings "4" and "04" instead of comparing them as integers.

I believe the easiest solution is as follows:
```
function is_electric() {
    LIST="4,5,7,8"
    DELIMITER=","
    VALUE=$1
    [[ "$LIST" =~ ($DELIMITER|^)*$VALUE($DELIMITER|$) ]]
}
```

It should also be possible to make LIST an indexed array of integers and check if 4 = 04 but I've found that regex operations on strings are a lot less hateful in bash.

**Comment by pasyn** [comment]
On second thought, an array would actually work better
Try this:
```
function is_electric() {
    LIST=(4 5 7 8)
    VALUE=$1
    [[ ${LIST[@]} =~ $VALUE ]]
}
```

**Comment by cpyarger** [comment]
I pulled your code in and now my meters aren't working 

Want to see if you can figure it out? I have to hit the hay for an early start at a jobsite tomorrow. 

here is the sample data 
```
{"Time":"2022-05-03T18:35:24.060447948-04:00","Offset":0,"Length":0,"Type":"SCM+","Message":{"FrameSync":5795,"ProtocolID":30,"EndpointType":156,"EndpointID":94032460,"Consumption":623418,"Tamper":4104,"PacketCRC":60025}}

Sending  {"state":"623418","attributes":{"unique_id":"94032460-sdrmr"}}  to http://supervisor/core/api/states/sensor.94032460 -- 200
```

**Comment by pasyn** [comment]
Looks like jq is spitting out a string with the word "null" instead of an actual null variable. Just need to change the if statement to match the word instead. I'll submit another pr shortly

**Comment by pasyn** [comment]
Looks like that did the trick! Check your if your meters are working. If they are good we can close this issue.

**Comment by cpyarger** [comment]
All good Thanks for the help
