### ISSUE TITLE
Water meter not working; Advice on migrating

### ISSUE THREAD

**Issue by esmoyer** [cpyarger/Home-Assistant-Addons#7]
**Describe the bug**
I have 1 issue and other is more a general question. 

1. QUESTION: Was just recommended this add-on coming from RTLAMR to MQTT. Was curious what the best approach to changing from RTLAMR to MQTT to this would be. I tried doing a "rip and replace", substituting the new sensors for their MQTT counterparts, which worked, but it threw all my readings off, so ended up restoring a backup. Any recommendations would be appreciated, as I am kind of stumped at the moment on the best way to approach this.

2. BUG: Working so far for my electric and gas meters, but no my water meter. It picks it up and returns the JSON in the debug log but says "Sending null..." and a sensor is never created for it.

**To Reproduce**
1. Run the add-on
4. Watch the debug log

**Expected behavior**
Pull in the data and create the sensor like electric and gas.

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
Here is what the debug logs shows for the water meter:
```
{"Time":"2022-05-11T11:44:19.672941168-05:00","Offset":0,"Length":0,"Type":"SCM","Message":{"ID":31500996,"Type":13,"TamperPhy":0,"TamperEnc":0,"Consumption":44805,"ChecksumVal":58702}}
Sending  null  to http://supervisor/core/api/states/sensor.31500996 -- 500
```

My config:
```
debug: true
msgType: scm
ids: 32642547,31500996,56916660
duration: 0
pause_time: 0
gas_unit_of_measurement: m³
electric_unit_of_measurement: kWh
water_unit_of_measurement: gal
scm_plus_gas_divisor: 1
```
Thank you!

**Comment by cpyarger** [comment]
It looks like there was a missing space where we generate the REST data for SCM water meters. It should be all good now

**Comment by cpyarger** [comment]
As for the question, this should generate new sensors for you, and i have some basic support for adjusting units and values in place without needing to use a template sensor. 

Do you have any more specifics on what sensors were messing up, and what values were output vs what should have been output?

**Comment by esmoyer** [comment]
Awesome, thanks for the quick work!

It's basically all three. My current setup creates sensors from the MQTT message from RTLAMR2MQTT and then from there I have a dozen or more templates sensors that take that data to create hourly, daily, monthly sensors as well as some others that use math to estimate daily and monthly cost (it's probably overkill, but I'm a data nerd)

I tried just swapping out the MQTT sensors for these new sensors which worked, but HA reads them as 0 and then when the first reading comes in all the sensors jump by whatever the reading is. Although, now that I am typing it out and thinking about it. I have not added the new sensors to Record, Logbook, History files so there is no history on them. Maybe once I add them and they retain some readings, I can swap them out and not get the big jump. I'll give it a go tonight and post back if it works to hopefully help others in the same boat.

Thanks!

**Comment by esmoyer** [comment]
Sorry, I just tried the "rebuild" on the add-on but it's still showing NULL; should there be an update?

**Comment by cpyarger** [comment]
You can also "check for updates" in the menu of the addon store

**Comment by esmoyer** [comment]
So all the data is pulling fine, just need to figure out how to make the switch without my values jumping. My idea didn't work. Will need to look into it more and will share what I find.

**Comment by esmoyer** [comment]
Yep, no luck. I thought I could manually update the main sensor and then start the add-on to avoid the jump but didn't work. I'll probably just bite the bullet and make the switch at the end of the month to avoid upsetting all of my stats. Thanks again!
