### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by jmort66** [cpyarger/Home-Assistant-Addons#8]
**Describe the bug**
's6-overlay-suexec: fatal: can only run as pid 1' when trying to start Add-on

**To Reproduce**
1. Go to SDR Meter Reader Add-on
2. Click on Start
3. Goto Log page
4. See error 's6-overlay-suexec: fatal: can only run as pid 1'

**Expected behavior**
no error

**Home Assistant OS**
Home Assistant OS 8.0
Kernel version 5.15.38
Agent version 1.2.1

**Additional context**
From my research, the config.yaml file should have the following line:
init: false
 
This is supposed to correct this issue as the updated s6-overlay in the newer version of Home Assistant is expecting only a single init call.

**Comment by cpyarger** [comment]
Hmm I dont see this issue when I run things, But I'll look into it

**Comment by pasyn** [comment]
I have a hunch as to what could cause this. Could you please post the yaml for your configuration?

**Comment by pasyn** [comment]
@cpyarger I was able to duplicate the issue by rebuilding the addon. Most likely caused by changes upstream.

**Comment by pasyn** [comment]
[https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/)

S6-Overlay update in Home Assistant is what I believe to be causing this issue. Currently testing a fix.

**Comment by jmort66** [comment]
This fixed the issue for me.  Thank you.
